name: build guest

on:
  push:
    tags:
        - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# this is needed to gain access via OIDC to the S3 bucket for caching
permissions:
  id-token: write
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RISC0_RUST_TOOLCHAIN_VERSION: 1.88.0
  RISC0_VERSION: 2.3.1

jobs:
  build-guest:
    runs-on: [ self-hosted, prod, Linux, X64, cpu ]

    steps:
      - name: clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install rust
        uses: risc0/risc0/.github/actions/rustup@fbe1d0bb75c21fe36cefd87bae25f424b711b291

      - name: Install sccache
        uses: risc0/risc0/.github/actions/sccache@fbe1d0bb75c21fe36cefd87bae25f424b711b291
        with:
          key: Linux-default

      - name: install cargo risczero
        uses: ./.github/actions/bininstall-risc0
        with:
          risczero-version: ${{ env.RISC0_VERSION }}
          toolchain-version: ${{ env.RISC0_RUST_TOOLCHAIN_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build guest with docker
        env:
          RISC0_USE_DOCKER: 1
        run: cargo build --manifest-path=crates/zkvm/Cargo.toml

      - name: compute image ids
        id: compute-image-ids
        run: |
          IMAGE_ID=$(r0vm --elf target/riscv-guest/zkvm/ntt_message_inclusion/riscv32im-risc0-zkvm-elf/docker/ntt_message_inclusion.bin --id)
          echo "image_id=$IMAGE_ID" >> $GITHUB_OUTPUT

      - uses: svenstaro/upload-release-action@v2
        with:
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/riscv-guest/zkvm/ntt_message_inclusion/riscv32im-risc0-zkvm-elf/docker/ntt_message_inclusion.bin
          asset_name: ${{ steps.compute-image-ids.outputs.image_id }}.bin
          tag: ${{ github.ref }}

      - name: Show sccache stats
        run: sccache --show-stats
